export const BASE_URL = 'https://prybar.onrender.com/api/v1'
export const SIGNUP_URL = 'auth/signup'
export const LOGIN_URL ='auth/signin'
export const PASSWORD_RECOVERY_URL ='auth/recover/generate'
export const RESET_PASSWORD_URL = 'auth/recover/confirm'
export const CREATE_EVENT = 'event'
export const GET_EVENTS = 'event'
export const GET_PARTICIPANTS = 'event/participants'
export const GOOGLE_CALENDER = 'calender'
export const GOOGLE_SIGN_UP = 'auth/google/auth'

